# Generated by Django 5.0.1 on 2024-02-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='upload/nft/')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('create_on', models.DateTimeField(auto_now=True)),
                ('update_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='social',
            options={'verbose_name': 'Соц. сети', 'verbose_name_plural': 'Соц. сети'},
        ),
        migrations.AlterField(
            model_name='social',
            name='icon',
            field=models.FileField(upload_to='uploads/social/'),
        ),
        migrations.AlterField(
            model_name='social',
            name='link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='social',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
